[tasks.bootstrap]
dependencies = [
  { name = "bootstrap", path = "./web" },
]

[tasks.build]
# This is needed because `build` is predefined in default.
clear = true
dependencies = [
  { name = "build", path = "./web" },
  { name = "ogp", path = "./build" },
]

[tasks.dev]
dependencies = [
  # TODO: replace Web build with Rust build
  { name = "dev", path = "./web" },
]

[tasks.start]
dependencies = [
  # TODO: replace Web build with Rust build
  { name = "start", path = "./web" },
]
