[tasks.bootstrap]
dependencies = [
  { name = "bootstrap", path = "./web" },
]

[tasks.build]
# This is needed because `build` is predefined in default.
clear = true
dependencies = [
  { name = "build", path = "./web" },
  { name = "run", path = "./lib" },
]
